### ISSUE TITLE
🐛 Only pulls title of first episode

### ISSUE THREAD

**Issue by addisonxx** [twocaretcat/watch-history-exporter-for-amazon-prime-video#1]
The script runs without any errors, but it only pulls the first episode title when multiple are watched on the same date. Is there any way you could edit it to include all of them? 

<img width="1663" alt="Screenshot 2024-12-01 at 21 03 31" src="https://github.com/user-attachments/assets/4cc0d639-b807-44bf-a1a6-e8ab59a4e3a1">
<img width="474" alt="Screenshot 2024-12-01 at 21 04 14" src="https://github.com/user-attachments/assets/2f850bb2-5059-4af1-8df4-6c54af94bb06">

**Comment by jerboa88** [comment]
Good catch! I've updated the script so it should work now for multiple movies/series/episodes on the same day.

**Comment by jerboa88** [comment]
Support for multiple episodes added in ff6323c6a90dc970bfad08bd6dcca0492d10d4ad.
Support for multiple movies/shows added in 7233c0439a7e451b8f77591d216d1849974dc83c.
